the_facebook/facebook/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as account_views



app_name = 'account'


urlpatterns = [
    path('signup-user/',account_views.Registration,name='register'),
    path('login-user/',auth_views.LoginView.as_view(template_name='account/login.html'),name='login'),
    path('logout-user/',auth_views.LogoutView.as_view(),name='logout')
]

the_facebook/facebook/facebook/urls.py
from django.contrib import admin
from django.urls import (path, include)
from . import views as main_views

from django.contrib.auth import views as auth_views


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',auth_views.LoginView.as_view(template_name='account/login.html'),name='login'),
    path('',main_views.HomeView.as_view(),name='home_index'),


    #account
    path('account/',include('account.urls',namespace='account')),
    path('account/',include('django.contrib.auth.urls')),

    #user
    path('users/',include('users.urls',namespace='users')),

    #post
    path('post/',include('post.urls',namespace='post')),



]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

the_facebook/facebook/post/urls.py
from django.urls import path
from post.views import (PostListView,UserPostListView ,PostDetailView,
                        PostCreateView, PostUpdateView,
                        PostDeleteView,
                        CommentCreateView)



app_name = 'post'


urlpatterns = [
    path('post-list/',PostListView.as_view(),name='post_list'),
    path('user/<str:username>/',UserPostListView.as_view(),name='user_post_list'),
    path('post-detail/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('post-create/',PostCreateView.as_view(),name='post_create'),
    path('post/<int:pk>/update',PostUpdateView.as_view(),name='post_update'),
    path('post/<int:pk>/delete/',PostDeleteView.as_view(),name='post_delete'),

    path('comment-create/',CommentCreateView.as_view(),name='comment_create')

]

the_facebook/facebook/users/urls.py
from users import views
from django.urls import path, include



app_name = 'users'

urlpatterns = [
    path('profile',views.ProfileView.as_view(),name='profile'),
    path('profile-update',views.update_profile,name='update_profile')




]

the_facebook/facebook/templates/base.html
{% load staticfiles  %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>The facebook</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/account/account.css' %}">
    <link rel="stylesheet" href="{% static 'css/post/post.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/users.css' %}">


    <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#3b5998 ;">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">



    {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'post:post_list' %}"><img src="{% static 'images/facebook_lg.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""></a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:profile' %}"><img src="{{user.profile.image.url}}" width="30" height="30" class="d-inline-block align-top" alt=""></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'account:logout' %}">Log out</a>
        </li>

        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'account:login' %}"><img src="{% static 'images/facebook_lg.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""></a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'account:register' %}" >register</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'account:login' %}">Log in</a>
        </li>

        {%endif%}

      </ul>

  </div>
</nav>










  </head>

  <body>




    <div class="container">
    {% block body_block %}



    {% endblock %}
    </div>


  </body>
</html>

the_facebook/facebook/templates/index.html
{% extends 'base.html' %}

{% block body_block %}
{% load staticfiles  %}

<div class="move">
  <h1>Home page</h1>
  <a href="{% url 'post:post_list' %}">list</a>
</div>




{% endblock %}