twitter_clone/twitter/account/urls.py
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path

app_name = 'account'

urlpatterns = [
        path('register/',views.register,name='register'),
        path('login/',auth_views.LoginView.as_view(template_name='account/login.html'),name='login'),
        path('logout/',auth_views.LogoutView.as_view(),name='logout'),

        



]

twitter_clone/twitter/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('posts-detail/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('user/<str:username>',views.UserPostListView.as_view(),name='user_post'),
    path('post/new/',views.PostCreateView.as_view(),name='post_create'),
    path('post/<int:pk>/update/',views.PostUpdateView.as_view(),name='post_update'),
    path('post/<int:pk>/delete/',views.PostDeleteView.as_view(),name='post_delete'),


]

twitter_clone/twitter/twitter/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from posts import views as postviews

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.HomeView.as_view(),name='home_index'),
    path('',postviews.PostListView.as_view(),name='home_index'),


    #account
    path('account/',include('account.urls',namespace='account')),
    # path('account/',include('django.contrib.auth.urls')),

    #user
    path('users/',include('users.urls',namespace='users')),

    #post
    path('posts/',include('posts.urls',namespace='posts')),


    #password reset
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='account/password_reset.html')
    ,name='password_reset'),

    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html')
    ,name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html')
    ,name='password_reset_confirm'),

    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html')
    ,name='password_reset_complete'),


]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

twitter_clone/twitter/users/urls.py
from users import views
from django.urls import path, include



app_name = 'users'

urlpatterns = [
    path('profile',views.ProfileView.as_view(),name='profile'),
    path('profile_update',views.update_profile,name='profile_update')




]

twitter_clone/twitter/templates/base.html
{% load staticfiles  %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Twitter</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">




  </head>
  <body>
    <nav class='navbar navbar-expand-lg navbar-light bg-light'>
      <div class="container">

        <ul class="navbar-nav">

          <li class='nav-item active'>
            <a class='navbar-brand' href="{% url 'home_index' %}">Tweet</a>
          </li>
          {% if user.is_authenticated %}

          <li class='nav-item active'>
            <a class='nav-link' href="{% url 'users:profile' %}"> <span class="glyphicon glyphicon-user"></span> Profile</a>
          </li>

           <li class='nav-item active'>
             <a class='nav-link' href="{% url 'posts:post_create' %}">Post</a>
           </li>

            <li class='nav-item active'>
              <a class='nav-link' href="{% url 'account:logout' %}">Log out</a>
            </li>


          {% else %}

          <li class="nav-item active">
            <a class='nav-link' href="{% url 'account:register' %}">Register</a>
          </li>
          <li class="nav-item active">
            <a class='nav-link' href="{% url 'account:login' %}"> <span class="glyphicon glyphicon-user"></span> Log In</a>
          </li>

          {% endif %}


        </ul>

      </div>

    </nav>

    <div class="container">
    {% block body_block %}


    {% endblock %}
    </div>



  </body>
</html>

twitter_clone/twitter/templates/index.html
{% extends 'base.html' %}

{% block body_block %}

<h1>Welcome to home page</h1>

{% endblock %}