twitter_clone/twitter/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('posts-detail/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('user/<str:username>',views.UserPostListView.as_view(),name='user_post'),
    path('post/new/',views.PostCreateView.as_view(),name='post_create'),
    path('post/<int:pk>/update/',views.PostUpdateView.as_view(),name='post_update'),
    path('post/<int:pk>/delete/',views.PostDeleteView.as_view(),name='post_delete'),


]

twitter_clone/twitter/twitter/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from posts import views as postviews

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.HomeView.as_view(),name='home_index'),
    path('',postviews.PostListView.as_view(),name='home_index'),


    #account
    path('account/',include('account.urls',namespace='account')),
    # path('account/',include('django.contrib.auth.urls')),

    #user
    path('users/',include('users.urls',namespace='users')),

    #post
    path('posts/',include('posts.urls',namespace='posts')),


    #password reset
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='account/password_reset.html')
    ,name='password_reset'),

    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html')
    ,name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html')
    ,name='password_reset_confirm'),

    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html')
    ,name='password_reset_complete'),


]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

twitter_clone/twitter/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class Post(models.Model):

    title = models.CharField(max_length=250)
    content = models.TextField()
    date_posted = models.TimeField(default = timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_detail',kwargs={'pk':self.pk})

twitter_clone/twitter/posts/views.py
from django.shortcuts import (render, get_object_or_404, redirect)
from django.views import generic
from posts.models import Post
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import (LoginRequiredMixin, UserPassesTestMixin)

# Create your views here.


class PostListView(generic.ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'posts/post_list.html'
    order_by = ['date_posted']
    paginate_by = 5



class UserPostListView(generic.ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'posts/user_posts.html'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User,username=self.kwargs.get('username',))
        return Post.objects.filter(author=user).order_by('-date_posted')





class PostDetailView(generic.DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin,generic.CreateView):
    model = Post
    fields = ('title', 'content',)

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,generic.UpdateView):
    model = Post
    fields = ('title', 'content')

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)


    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,generic.DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

twitter_clone/twitter/posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}

{% block body_block %}

<p></p>
<div class="container">
  <div class="jumbotron">
    <h3>Delete Post?</h3>

      <form method="POST">
        {% csrf_token %}
        <h2>Are you sure to delete <strong>"{{object.title}}"</strong> post</h2>

        <button class="btn btn-danger" type="submit">Yes</button>

        <a class="btn btn-success"href="{% url 'posts:post_detail' pk=object.pk %}">No</a>


      </form>
  </div>
</div>


{% endblock %}

twitter_clone/twitter/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block body_block %}

<p></p>
<div class="container">


    <div class="card mb-3">
      <img class="rounded-circle account-img" width="68 "height="68"src="{{  object.author.profile.image.url }}" alt="Card image cap">
        <div align=''>
          <p class="card-title"><a href="{% url 'posts:user_post' object.author.username %}">{{object.author}}</a></p>
        </div>
        <div class="card-body">
          <h3 class="card-title">{{object.title}}</h3>
          <p2 class="card-text">{{object.content}}</p2>
          <p class="card-text"><small class="text-muted">{{object.date_posted}}</small></p>
        </div>
    </div>
    {% if object.author == user %}
      <div class="">
        <a class="btn btn-success" href="{% url 'posts:post_update' pk=object.pk%}">Update</a>
        <a class="btn btn-danger" href="{% url 'posts:post_delete' pk=object.pk %}">Delete</a>
      </div>
    {% endif %}



</div>

{% endblock %}

twitter_clone/twitter/posts/templates/posts/post_form.html
{% extends 'base.html' %}

{% block body_block %}

{% load bootstrap4 %}

<p></p>
<div class="container">
  <div class="jumbotron">
    <h3>Create Post</h3>

      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <table>{% bootstrap_form form %}</table>

        <input class="btn btn-success" type="submit" name="" value="Submit">
      </form>
  </div>
</div>


{% endblock %}

twitter_clone/twitter/posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block body_block %}

<p></p>
<div class="container">
  {% if user.is_authenticated %}
    <a href="{% url 'posts:post_create' %}">
      <span class="glyphicon glyphicon-plus"></span> Add post
    </a>

  {% endif %}
  <p></p>
  {% for post in  post_list %}
  <div class="card mb-3">
    <img class="rounded-circle account-img" width="68 "height="68"src="{{  post.author.profile.image.url }}" alt="Card image cap">
      <div align=''>
        <p class="card-title"> <a href="{% url 'posts:user_post' post.author.username %}">{{post.author}}</a></p>
      </div>
      <div class="card-body">
        <h3 class="card-title"> <a href="{% url 'posts:post_detail' pk=post.pk %}">{{post.title}}</a></h3>
        <p class="card-text"><small class="text-muted">{{post.date_posted}}</small></p>
      </div>
  </div>
  {% endfor %}

  {% if is_paginated %}

    {% if page_obj.has_previous %}
      <a class='btn btn-outline-info' href="?page=1">First</a>
      <a class='btn btn-outline-info' href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}

      {% if page_obj.num == num %}
        <a class='btn btn-info' href="?page={{num}}">{{num}}</a>

      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'  %}
        <a class='btn btn-outline-info' href="?page={{num}}">{{num}}</a>

      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class='btn btn-outline-info' href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class='btn btn-outline-info' href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}

  <p></p>

</div>

{% endblock %}

twitter_clone/twitter/posts/templates/posts/user_posts.html
{% extends 'base.html' %}

{% block body_block %}


<p></p>
<h1 class="mb-3">Posts by {{view.kwargs.user}} {{ page_obj.paginator.count }}</h1>
<div class="container">
  {% if user.is_authenticated %}
    <a href="{% url 'posts:post_create' %}">
      <span class="glyphicon glyphicon-plus"></span> Add post
    </a>

  {% endif %}
  <p></p>
  {% for post in  post_list %}
  <div class="card mb-3">
    <img class="rounded-circle account-img" width="68 "height="68"src="{{  post.author.profile.image.url }}" alt="Card image cap">
      <div align=''>
        <p class="card-title"> <a href="{% url 'posts:user_post' post.author.username %}">{{post.author}}</a></p>
      </div>
      <div class="card-body">
        <h3 class="card-title"> <a href="{% url 'posts:post_detail' pk=post.pk %}">{{post.title}}</a></h3>
        <p2 class="card-text">{{post.content}}</p2>
        <p>lets see {{post.author.profile.biography}}</p>

        <p class="card-text"><small class="text-muted">{{post.date_posted}}</small></p>
      </div>
  </div>
  {% endfor %}








  {% if is_paginated %}

    {% if page_obj.has_previous %}
      <a class='btn btn-outline-info' href="?page=1">First</a>
      <a class='btn btn-outline-info' href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}

      {% if page_obj.num == num %}
        <a class='btn btn-info' href="?page={{num}}">{{num}}</a>

      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'  %}
        <a class='btn btn-outline-info' href="?page={{num}}">{{num}}</a>

      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class='btn btn-outline-info' href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class='btn btn-outline-info' href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}

  <p></p>

</div>

{% endblock %}